default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres-db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test
